# Generated by Django 5.2.1 on 2025-05-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('FACIL', 'Facil'), ('MEDIO', 'Medio'), ('AVANÇADO', 'Avançado')], default='', max_length=100)),
                ('combo', models.TextField()),
            ],
        ),
    ]
