# Generated by Django 5.2.1 on 2025-05-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fighters/'),
        ),
    ]
