# Generated by Django 5.2.1 on 2025-05-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_fighter_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
